### ISSUE TITLE
Network usage

### ISSUE THREAD

**Issue by ChangSpivey** [petr-stety-stetka/gnome-usage#1]
How do you plan on retrieving per-process network usage? I'm asking because I published [netinfo](https://github.com/ChangSpivey/netinfo) a few days ago specifically with Gnome Usage in mind. It seems it was just in time :)

It's written in Rust though, but I wouldn't mind writing a C Interface if you're interested. That should only take a couple of days at maximum....

But maybe there is a better alternative I'm not aware of?

Either way, I'm excited to see Usage getting in shape!

**Comment by petr-stety-stetka** [comment]
Hi, I like your library, it looks very simple and pretty. I think that would be a good idea to use it, 
It would be great if you could write a C interface. 
Then I'll be able to use in Usage.

**Comment by ChangSpivey** [comment]
C interface now available at [netinfo-ffi](https://github.com/ChangSpivey/netinfo-ffi). This issue is related to https://github.com/ChangSpivey/netinfo/issues/2.

**Comment by petr-stety-stetka** [comment]
I have managed to successfully write vapi file for NetInfo-ffi and thus connect rust-->c library with gnome-usage (Vala). 

Version 0.2.7 has a test demo output of network usage to the terminal with NetInfo.

That remains is to connect backend (and UI) with NetInfo API. I think that in the next version will have a working net monitoring in Usage!

Thx ChangSpivey for netinfo library.

**Comment by petr-stety-stetka** [comment]
Usage 0.3.0 has implemented showing Network load, but it still yet need some tweaks.

**Comment by petr-stety-stetka** [comment]
In Usage 0.3.6, I did some tweaking about showing network load. Now is it much better. And I think that this issue can be closed. It still remains to do Data usage, but I think this issue doesn't relevant to it.
