### ISSUE TITLE
Rename application id

### ISSUE THREAD

**Issue by mvaello** [petr-stety-stetka/gnome-usage#7]
Compared to other new GNOME apps the current application id is "org.gnome.usage" but is common to use capital letter for the first letter like this: "org.gnome.Usage", I think that this can solve some future issues with namesapces and other wierd things.

I can push a patch if you agree.

**Comment by mvaello** [comment]
A bunch of examples:

- org.gnome.Books     
- org.gnome.Builder   
- org.gnome.Calculator
- org.gnome.Calendar  
- org.gnome.Characters
- org.gnome.Devhelp   
- org.gnome.Dictionary
- org.gnome.Documents 
- org.gnome.Epiphany  
- org.gnome.Evince    
- org.gnome.Games     
- org.gnome.Geary     
- org.gnome.Glade     
- org.gnome.Maps      
- org.gnome.Nautilus  
- org.gnome.Photos    
- org.gnome.Polari    
- org.gnome.Rhythmbox3
- org.gnome.Todo      
- org.gnome.Totem     
- org.gnome.Weather

**Comment by petr-stety-stetka** [comment]
Thanks, I fixed it. [Commit ](https://github.com/petr-stety-stetka/gnome-usage/commit/c9d3c936ed7ea527dc79dda237159e7aa6835122) It was typing error.
