### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by mvaello** [petr-stety-stetka/gnome-usage#8]
Estoy intentando construir la aplicación como siempre usando la rama principal pero consigo el error siguiente:

```

$ LANG=C make -j3                                                  
[  1%] Performing build step for 'netinfo'
[  1%] Built target i18n
[ 32%] Built target egg
[ 42%] Built target rg
CMake Error at /home/*********/Workspace/gnome-devel/checkout/gnome-usage/build/external/netinfo/netinfo-prefix/src/netinfo-stamp/netinfo-build-Release.cmake:16 (message):
  Command failed: 1

   '/usr/bin/cmake' '-Dmake=' '-Dconfig=' '-P' '/home/*********/Workspace/gnome-devel/checkout/gnome-usage/build/external/netinfo/netinfo-prefix/src/netinfo-stamp/netinfo-build-Release-impl.cmake'

  See also

    /home/*********/Workspace/gnome-devel/checkout/gnome-usage/build/external/netinfo/netinfo-prefix/src/netinfo-stamp/netinfo-build-*.log


external/netinfo/CMakeFiles/netinfo.dir/build.make:110: recipe for target 'external/netinfo/netinfo-prefix/src/netinfo-stamp/netinfo-build' failed
make[2]: *** [external/netinfo/netinfo-prefix/src/netinfo-stamp/netinfo-build] Error 1
CMakeFiles/Makefile2:173: recipe for target 'external/netinfo/CMakeFiles/netinfo.dir/all' failed
make[1]: *** [external/netinfo/CMakeFiles/netinfo.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 43%] Built target usage_gresource_xml
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

I'm not sure but I guess that's something related or missing for build netinfo dependency. Any idea about how to fix this?

Thanks.

**Comment by petr-stety-stetka** [comment]
netinfo is rust library, so you must have installed cargo and rust.

Dou you can paste here  /home/*********/Workspace/gnome-devel/checkout/gnome-usage/build/external/netinfo/netinfo-prefix/src/netinfo-stamp/netinfo-build-*.log please?

**Comment by mvaello** [comment]
Ok, I assumed it would be something related to rust. I forget to take a look into the err log, and is pretty clear:

```
  Command failed (No such file or directory):

   'cargo' 'build'

```

So in some way the app have a new dependecy to check before the build, rust ;-).

Thanks.

**Comment by petr-stety-stetka** [comment]
I added check if is rust and cargo installed. Commit [86b6c71819d48f469ffc938a9b9818086fb16c10](https://github.com/petr-stety-stetka/gnome-usage/commit/86b6c71819d48f469ffc938a9b9818086fb16c10)
