### ISSUE TITLE
Use GNOME style versioning

### ISSUE THREAD

**Issue by mvaello** [petr-stety-stetka/gnome-usage#9]
According to the [official documentation](https://developer.gnome.org/programming-guidelines/stable/versioning.html.en), most GNOME apps follow a versioning convention, so I think that GNOME Usage should not be an exception, isn't it?

**Comment by petr-stety-stetka** [comment]
You have right. However, on official numbering I plan to switch soon as application will be more complete.

**Comment by mvaello** [comment]
Ok, great. Probably, reach the sable 1.0 could be a good momento to switch.

**Comment by petr-stety-stetka** [comment]
I think too :)
